version: 2
builds:
  - main: .
    ldflags:
      - -s -w
    flags:
      - -trimpath
    binary: 'pomo'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
